### ISSUE TITLE
Server crash after 2022/06/24 CS:GO update

### ISSUE THREAD

**Issue by nuclearsilo583** [komashchenko/ParticleFix#3]
OS: Windows
Using with the official fixed build of SM (6544) and MM (1147) still crash if this plugin is enabled.

**Comment by BlueSkyClouds** [comment]
just rebuild once
https://github.com/BlueSkyClouds/ParticleFix/actions/runs/2557458410

**Comment by komashchenko** [comment]
Building with new SDK https://github.com/komashchenko/ParticleFix/releases/tag/v1.0.1-new-sdk
