### ISSUE TITLE
Compatibility with GOTV

### ISSUE THREAD

**Issue by Erik-97** [komashchenko/ParticleFix#6]
Hi, if i use this plugin i can't connect on my servers via GOTV because class tables are different, is there a way to fix this without removing the plugin?

![unknown](https://user-images.githubusercontent.com/47022164/187750365-e68c0dcd-302a-4685-b9dd-7f17da6c2ce4.png)

**Comment by domikuss** [comment]
Hi, @komashchenko fixed this on [1.0.2 version](https://github.com/komashchenko/ParticleFix/releases/tag/v1.0.2)
