### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by MiguelitoS2** [komashchenko/ParticleFix#8]
Hello,

Getting this error while plugin is trying to load:
06/12/2023 - 09:13:49: LimitExtender: Failed to find CServerGameDLL::CreateNetworkStringTables.
Log File: [https://www.odrive.com/s/420f4965-5d3f-4218-8670-8bcdc010ab14-648ef3b5](url)

Running CS:GO

] meta version
Metamod:Source Version Information
Metamod:Source version 1.11.0-dev+1148
Plugin interface version: 16:14
SourceHook version: 5:5
Loaded As: Valve Server Plugin
Compiled on: Jun 26 2022 08:01:45
Built from: https://github.com/alliedmodders/metamod-source/commit/4bdc218
Build ID: 1148:4bdc218
http://www.metamodsource.net/

] meta list
Listing 9 plugins:
[01] SourceMod (1.11.0.6934) by AlliedModders LLC
[02] Stripper (1.2.2) by BAILOPAN
[03] CSGO-ArmsFix (1.0) by Kyle (4y)
[04] CS Tools (1.11.0.6934) by AlliedModders LLC
[05] SDK Tools (1.11.0.6934) by AlliedModders LLC
[06] SDK Hooks (1.11.0.6934) by AlliedModders LLC
[07] PTaH (1.1.4-b3a9ea6) by Phoenix (˙·٠●Феникс●٠·˙)
[08] DHooks (1.11.0.6934) by AlliedModders LLC
[09] SteamWorks Extension (1.2.2) by Kyle Sanderson

] plugin_print
Loaded plugins:
---------------------
0:	"Metamod:Source 1.11.0-dev+1148"
---------------------

sm version
 SourceMod Version Information:
    SourceMod Version: 1.11.0.6934
    SourcePawn Engine: 1.11.0.6934, jit-x86 (build 1.11.0.6934)
    SourcePawn API: v1 = 5, v2 = 16
    Compiled on: Mar  3 2023 21:08:09
    Built from: https://github.com/alliedmodders/sourcemod/commit/b09a675e
    Build ID: 6934:b09a675e
    http://www.sourcemod.net/

Cheers

**Comment by komashchenko** [comment]
Hi, the information provided is insufficient

**Comment by MiguelitoS2** [comment]
@komashchenko 
Updated with more info!
tell me if you need more info

**Comment by komashchenko** [comment]
ParticleFix version 1.0.3 ?
Disable Metamod for the test and check if it works via plugin_print

**Comment by MiguelitoS2** [comment]
> ParticleFix version 1.0.3 ? Disable Metamod for the test and check if it works via plugin_print

Hello

ParticleFix Version is 1.0.3 which is latest
I have disabled metamod and this is what i get after i do plugin_print.

```
] plugin_print
Loaded plugins:
---------------------
---------------------
```

**Comment by komashchenko** [comment]
Run server validation and check again, it can not fail to run on the current version of the game (1.38.7.9), when no other plugins besides it does not

**Comment by MiguelitoS2** [comment]
> Run server validation and check again, it can not fail to run on the current version of the game (1.38.7.9), when no other plugins besides it does not

okay yeap that fixed it thanks Koma! sorry about this .. you can close this.

Issue is solved.

```
] plugin_print
Loaded plugins:
---------------------
0:	"ParticleFix (1.0.3) by Phoenix (˙·٠●Феникс●٠·˙)"
1:	"Metamod:Source 1.11.0-dev+1148"
---------------------
```
